name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - run: mise run fix-rrrocket

      - uses: astral-sh/setup-uv@v4

      - run: uv sync

      - run: mise exec -- uv run pytest
